repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  # Local ESLint
  - repo: local
    hooks:
      - id: eslint-client
        name: ESLint Client
        entry: bash -c "cd client && npx eslint ."
        language: system
        pass_filenames: false

      - id: eslint-server
        name: ESLint Server
        entry: bash -c "cd server && npx eslint ."
        language: system
        pass_filenames: false
