# ─────────────────────────────────────────────────────────────────
# Kubernetes Secrets
# In production these would come from AWS Secrets Manager
# For this project we use K8s native secrets
# ─────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mern-prod
type: Opaque
data:
  mongodb-uri:      bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9tZXJuZGI=
  mongodb-password: TW9uZ29TZWN1cmVAMjAyNg==
